server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/money_book?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: moneybook
    password: moneybook1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    com.moneybook: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
